### ISSUE TITLE
Monospaced font when displaying a message with a HTML pre-tag

### ISSUE THREAD

**Issue by Neui** [mailchuck/PyBitmessage#106]
When trying to display a message with <pre> tags in them, the <sub>(text)</sub>box <sup><sub>(where the message are displayed)</sub></sup> might be always monospaced, even on other messages. I only tried in the "Chans"-Tab, but it didn't affected the "Subscription"-Tab.
It doesn't always happen and might require a few tries.

See the following animation: ([Link](https://i.imgur.com/yT3JNRt.gif) or [gifv](https://i.imgur.com/yT3JNRt.gifv)) <sub>(Warning: might contain NSFW-Content (but just a little))</sub>
![Animation demonstrating the issue](https://i.imgur.com/yT3JNRt.gif)

I am using Windows 7 x64 using Python 2.7.9. I am running from source (currently 891e3d6517e4a76367802b97397c5038a5ca3b4c)

<sub><sup>The <pre>-tag displays the text inbetween it in a monospaced font and respects the space, making it good for ascii arts.<sup></sub>

**Comment by PeterSurda** [comment]
Thank you, I know that there is some sort of problem with changing fonts and I recall there is an issue open somewhere in the official PyBitmessage about this already. This will help me to reproduce and fix it.

**Comment by PeterSurda** [comment]
I am able to reproduce it now.
