### ISSUE TITLE
Close [X] - Minimize to tray

### ISSUE THREAD

**Issue by HostFat** [mailchuck/PyBitmessage#113]
Can you even add the possibility to set the [X] function to minimize it to the tray? (instead of closing it)
I mean new checkbox on the User Interface settings.

**Comment by PeterSurda** [comment]
There already is a similar ticket: Bitmessage#803. But I think yours is slightly different.

**Comment by PeterSurda** [comment]
Fixed in 23c07c4419f7973ebe3bafa5f10b39f9e266e8d7
