### ISSUE TITLE
Option to start objects unexpanded

### ISSUE THREAD

**Issue by fratermus** [mailchuck/PyBitmessage#119]
It seems the default behaviour is to expand all Identities, Chans, and Subscriptions by Default.  This results in a lot of information to wade through to find new messages.

Perhaps it would be productive to default to unexpanded, and maybe expand those that have new messages?  Or sort them to the top?  I know they are currently bolded but the effect is subtle.

**Comment by PeterSurda** [comment]
It is planned that UI saves the expanded status upon restart. However I haven't found out how to do that without leaking data correctly yet.
See #22.

**Comment by PeterSurda** [comment]
Also #12.

**Comment by PeterSurda** [comment]
Also, you don't need to expand it to view new messages. Selecting an account/subscription/chan root should produce the same list as selecting its inbox.
