### ISSUE TITLE
Sending time instead of receiving time

### ISSUE THREAD

**Issue by PeterSurda** [mailchuck/PyBitmessage#123]
Maybe the time displayed should work differently. The column label says "Received", but that might not be what the users expects. Messages are often received out of order and this screws up reading of threads.

Currently the message does not contain any information about sending time. It contains a proof of work and expiration time. The recipient verifies if the proof of work is sufficient for the delta time between now and expiration time. I believe this has been done in order to improve anonymity, as it's not possible to find out the sending time from the object that way. We can only, based on the PoW value, estimate a minimum for the sending time (it can't have been sent earlier than the calculated time).

**Comment by mofosyne** [comment]
Good idea. If you do worry about timespoofing, you could perhaps  do a blockchain (or chain hashing) of parent messages (or a random old message if no parent). Won't be perfect, but would at least keep the order correct (if most people are not lying about the time).

**Comment by PeterSurda** [comment]
As this data is not available and making it available would negatively influence anonymity, I recommend scrapping this, until a new message version is created. This will have the ability to have message headers including references to previous messages in conversions, and this will allow correct ordering and threading in the UI without needing to determine the sending time.
