### ISSUE TITLE
Renaming of Email Gateway accounts

### ISSUE THREAD

**Issue by PeterSurda** [mailchuck/PyBitmessage#134]
Currently you can only register/unregister.

**Comment by ghost** [comment]
Does renaming mean associating the bitmessage address with a new email address?

Or associating a new bitmessage address with the same email address?

**Comment by PeterSurda** [comment]
First of all, this requires support on the server, which isn't implemented. The idea is that if you want, you can rename your email address on the server by simply changing the label locally in PyBitmessage. So it's the first option.

Now that I think about it, it probably isn't such a great idea and causes security problems. You can just create a new address and register that and discontinue or even unregister the old one. Traditional email providers also usually won't allow you to change email addresses of your accounts. If the old account had a subscription, that may cause a billing issue but I'm willing to deal with it if it happens.
