### ISSUE TITLE
right click on account for register/unregister/status/settings

### ISSUE THREAD

**Issue by mailchuck** [mailchuck/PyBitmessage#14]
- [x] register and unregister now available
- [x] request new address if registration denied
- [x] settings
- [x] status
- [x] shorter TTL when sending these messages

**Comment by PeterSurda** [comment]
register/unregister stopped working

**Comment by PeterSurda** [comment]
Settings and TTL addressed in 50293860001a7b0030551e61d6f78cc507f0f3a1, just forgot to reference it in the commit message.
