### ISSUE TITLE
Maximum difficulty sanity check

### ISSUE THREAD

**Issue by PeterSurda** [mailchuck/PyBitmessage#144]
Some guy sent me a message, but his pubkey has a required difficulty ridiculously high, like 10e17, so noone can send meessages to him/her.

The client should estimate what difficulty it can realistically manage to do a PoW for and complain if you try to send to a higher one, not merely check maximum difficulty setting.

**Comment by mendaxi** [comment]
that's actually pretty funny

**Comment by PeterSurda** [comment]
Indeed
