### ISSUE TITLE
Headless mode allegedly doesn't work

### ISSUE THREAD

**Issue by PeterSurda** [mailchuck/PyBitmessage#161]
It was reported over BM that headless mode doesn't work. I haven't tested it in the mailchuck fork for a while so it's possible.

**Comment by rouben** [comment]
Seems to work for me, release v0.5.6 (e45e051) on win32. UI doesn't load, and process appears to run in the background. I didn't do more thorough testing, however.

**Comment by PeterSurda** [comment]
Perhaps I should add the report said it was on linux.

**Comment by DocElastic** [comment]
I have tested the mailchuck fork (v 0.5.6; `git clone`'d this week) on Ubuntu with `daemon=true`. Sending messages and retrieving inbox messages through the API works fine. There does not seem to be a problem.

**Comment by PeterSurda** [comment]
Perhaps I should also add that the error the reporter was getting was something like "Cannot connect to X". Perhaps it's still broken when either DISPLAY is unset or doesn't have access to the X server.

**Comment by rouben** [comment]
Ah, that changes things. If X11 is a requirement of daemon mode, then I'd flag that as a legit bug... unless that's actually desired? I don't see why it would be, though.

**Comment by mendaxi** [comment]
It might've been left out of the dependencies on accident.

**Comment by PeterSurda** [comment]
I can reproduce it, it's a bug that is triggered when PyQt is not installed. There was a missing check for daemonised mode.
