### ISSUE TITLE
Windows binary requires msvcr120.dll

### ISSUE THREAD

**Issue by PeterSurda** [mailchuck/PyBitmessage#173]
I got a report that on XP, it reports that msvcr120.dll is missing. Probably becuase the build environment has a newer MSVS installed.

**Comment by ghost** [comment]
What about compiling with MinGW instead? That might solve the problem.

**Comment by PeterSurda** [comment]
MinGW causes different issues, for example it causes UPX-ed binary to crash. I can look at it some other time to make sure it works for MinwGW too but it's not a priority.

I had to recompile python and some other stuff, and one of those things wouldn't build with MSVS 2008, so I installed 2012 and this introduced this bug. The solution is easy, I just have to bundle the dll in the spec file. But the report came after 0.5.7 was released and it didn't trigger on my windows test machine, it probably had the dll from somewhere else.

**Comment by PeterSurda** [comment]
Fixed in cf09872d67667d992caaec6fc60d6b5182498e01
