### ISSUE TITLE
typo in project info

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [mailchuck/PyBitmessage#187]
currently the project info for (1) says: 
"Bitmessage client with imporoved user interface and email gateway integration https://mailchuck.com"

please change: imporoved 
to: improved

(1) https://github.com/mailchuck/PyBitmessage

**Comment by PeterSurda** [comment]
Thanks for the report, since I hope to soon merge everything into the official repo and discontinue this one and then I have to change the description anyway (to explain that this has been discontinued), I'm not going to address this.
