### ISSUE TITLE
How can I force BitMessage to use Portable Mode by DEFAULT?

### ISSUE THREAD

**Issue by ghost** [mailchuck/PyBitmessage#194]
Portable Mode should be default; if not, BM will create BM files to the system itself(when first run). Forensics will know the user is using BM from these files/write to the system.

**Comment by PeterSurda** [comment]
You can create a basic keys.dat in the same directory as Bitmessage.exe and then run it.

**Comment by krikmo** [comment]
@verycrypt, [this](https://bitmessage.org/wiki/Keys.dat#.5BDEFAULT.5D_and_.5Bbitmessagesettings.5D) is the wiki article about keys.dat. Not sure what basic means here.

**Comment by PeterSurda** [comment]
I don't know off the top of my head what the minimal requirements for portable mode keys.dat are. Maybe creating an empty one is sufficient but I'm not sure.
