### ISSUE TITLE
Bitmessage without GUI

### ISSUE THREAD

**Issue by ghost** [mailchuck/PyBitmessage#195]
The official Bitmessage is pretty dead, so I'm asking it here.

In the future update, will you consider spliting GUI and core?
GUI ... python UI
Core ... open local port for API

Also, spliting into 2 will enable ARM device(e.g., raspberrypi) to act as a server.

ClientPC[BM UI]====>Headless Pi[Core]<----->Internet.

**Comment by PeterSurda** [comment]
There is already a ticket about this (probably even more than one).

This fork will soon be merged into the official PyBitmessage repo and then discontinued.
