### ISSUE TITLE
Any idea for opening "email gateway" service?

### ISSUE THREAD

**Issue by ghost** [mailchuck/PyBitmessage#196]
Email gateway: currently only @mailchuck.com is available.
1. Do you have a plan to share some code with us? Closed source could have potential bugs.
2. If you share some of them, I can open my own email gateway.

Let me know what you think.

(I admit, $1/mo for "Send emails" is cheap, but in my service, I will allow unlimited
mailchuck'<--->mailchuck' (same domain) mail FREE.)

**Comment by PeterSurda** [comment]
The code is here:
https://github.com/PeterSurda/bitmessage-email-gateway
