### ISSUE TITLE
idea: signatures

### ISSUE THREAD

**Issue by ghost** [mailchuck/PyBitmessage#48]
identity aware ( and optional: recipent aware ) signatures which can be set in textfile config and/or GUI:

for example:
BM-long1 can include "signature 1", as I know this is the one I message people with I know,
BM-long2 shouldn't do this as it is a channel,
BM-long3 shouldn't do this as well because I message to channels/lists with this,
BM-long4 should include "signature 2" because for whatever reason,
etc.

**Comment by PeterSurda** [comment]
Duplicate of Bitmessage#813
