### ISSUE TITLE
bug: reply on decentralized lists is broken

### ISSUE THREAD

**Issue by ghost** [mailchuck/PyBitmessage#49]
with the current fork version, replying to decentralized lists (subscriptions) is broken.
"It just does not work" is no good feedback as it lacks the specific "what", but I can't spot the error in the verbose fast scrolling output.

**Comment by mailchuck** [comment]
Ok I got the error, I'll fix it later today or early tomorrow.

**Comment by mailchuck** [comment]
In general if you describe what you're doing sufficiently I should be able to produce the backtrace myself.

**Comment by ghost** [comment]
in general:

upstream client (not mailchuck): open any conversation in a decentralized list, click reply, replying works.
mailchuck fork: open any conversation in the rider/tab for subscriptions, click reply, nothing anywhere happens to show me a text to edit a reply or anything reply-send able.

**Comment by PeterSurda** [comment]
Yea that's fine, I got this one, I was able to reproduce it and I know how to fix it. I meant that in the future, don't worry about not having the trace yourself, as long as I can reproduce it, it's fine.

**Comment by ghost** [comment]
Oh, I did not parse the sentence correctly.
Okay, thanks!

**Comment by mailchuck** [comment]
Latest commit addresses it. The UI works correctly now, but I don't have a good way to test whether actual sending works too. Can you let me know?

**Comment by ghost** [comment]
I pulled the changes, but this opens up another subissue:
trying to send it via a decentralized list (where I in the original client have the choice to send from my identity) now gives me):
- hit reply
- get "Send Message to your Subscribers" filled with text, okay so far, but:
- get only a selection of From: "Subscription" adressess. this is not how some of the subscription addresses I have work (which are interactive discussion lists).
- okay, no problem let me try to send it from the address and not to the address.
- result: 

To: Broadcast subscribers
From: Broadcast BM ID (i think)
Subject: whatever i put there
Body: whatever i wrote
status: Error! Could not find sender address (your address) in the keys.dat file.

Subidea: integration for a "sent" (messages I did sent via this decentralized list / subscriptions) in the subscriptions section.
There are subscriptions and lists(still subscriptions technically) in my "Subscriptions" tab/rider of the fork.

**Comment by mailchuck** [comment]
Ok, I am not fully sure I understand this. What you describe, and what is labeled "decentralized list", is called "chan" in the UI. Subscriptions, on the other hand, are broadcasts: there is no recipient address, only sender.

Maybe if you could give me an example of such a list that I can test myself.

**Comment by ghost** [comment]
Can you generate a bitmessage identity to which I can send you the list BM?
I am 100% sure that when it's not even listed on the .onion of EDN, that it's not liked to be seen on github.com
You can find my public bitmessage on krosos.sdf.org

**Comment by ghost** [comment]
Hi, in before you receive the bitmessage:

don't use the list for that purpose (or at all?).
I send out 2 more messages, one containing the testing purpose list.
Everything where I am is slow, so you will get 3 messages before the list one arrives.

**Comment by PeterSurda** [comment]
No problem.

**Comment by mailchuck** [comment]
Bad wording on commit autoclosed. It works now the same way as in the old client. I tested it on AyrA's 24/7 mailing list. You can close the issue yourself if you want, or I can do it after you're happy.

**Comment by ghost** [comment]
I pulled the latest master and I am not sure if this is still related to the original issue.
I am trying to get some info and clarification on bitmessage use now to see if it's just a misunderstanding on my side.

**Comment by ghost** [comment]
I'm doing one last test, when I get the message it is solved on my side and I will close the issue.

**Comment by ghost** [comment]
seems solved.

**Comment by ghost** [comment]
I am unsure if this is related, heavy on memory while compiling other things, but trying to send out an broadcast (decentralized list called here earlier) just segfaulted.

**Comment by PeterSurda** [comment]
yes I know the sending of broadcasts is broken at the moment, see #51.

**Comment by mailchuck** [comment]
Latest commit fixes this, but note #57.
