### ISSUE TITLE
￼￼check if updateSentItemStatusByAckdata is processed correctly

### ISSUE THREAD

**Issue by PeterSurda** [mailchuck/PyBitmessage#54]
- I have the impression that when PoW starts, the status isn't immediately updated in the message list. It needs to be checked and if broken fixed

**Comment by mailchuck** [comment]
It looks like it works fine, but it displays misleading messages, 'doingmsgpow' status is translated by the UI as "Need to work to send message. Work is queued". Only the background thread sets it to "Doing work necessary to send message". But when you switch to "sent" folder afterwards, it forgets what is being worked on now, so the first message shows.

**Comment by PeterSurda** [comment]
Yep that was broken, it's fixed now.
