### ISSUE TITLE
reply is broken

### ISSUE THREAD

**Issue by ghost** [mailchuck/PyBitmessage#62]
Currently (latest master), hitting reply in "Messages" view does nothing.
Sorry if I already addressed this in past issues.

**Comment by mailchuck** [comment]
I'm sorry I can't reproduce it. Are you maybe replying to a mailing list which you host yourself? Please add a new subscription, BM-2cWQ2LQpMRtJEhrvg27m2qxrZYLEyzW19M, that is my testing mailing list. Send some messages to it and then I'll test.

**Comment by ghost** [comment]
No, this is in an ongoing person to person dialogue, not any kind of list or broadcast.

**Comment by mailchuck** [comment]
Does the console output show any errors? Does it happen after you restart bitmessage as well?

**Comment by ghost** [comment]
trailing part of file location replaced by (...)
this happens when I rightclick -contextmenu- select reply:

Traceback (most recent call last):
  File "(...)/PyBitmessage/src/bitmessageqt/**init**.py", line 2862, in on_action_InboxReply
    acct.parseMessage(toAddressAtCurrentInboxRow, fromAddressAtCurrentInboxRow, str(tableWidget.item(currentInboxRow, 2).data(Qt.UserRole).toPyObject()), messageAtCurrentInboxRow)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-12: ordinal not in range(128)

**Comment by mailchuck** [comment]
Ah yes, there's some weird characters either in the subject or in body. I think I know how to reproduce it now.

**Comment by ghost** [comment]
it was unicode set i think, äöü something

**Comment by mailchuck** [comment]
Yep, I got it now, it's unicode in the subject. I'll fix it right away.

**Comment by mailchuck** [comment]
Reopen if still not working.
