### ISSUE TITLE
Arrow keys doesn't work

### ISSUE THREAD

**Issue by Neui** [mailchuck/PyBitmessage#65]
In the old client, i could navigate through the messages with the arrow-keys, select multiple ones by holding shift and press DEL to delete them.. Well, the arrow-keys-thing doesn't work.

So, I'd like to have that functionality back.

I am using the Windows-Version, v0.4.5.2. I am mostly in the chans-tab, so i only tested it there.

**Comment by PeterSurda** [comment]
The focus that gets key signals is probably on a different part of the window. Just click somewhere in the message list, and then the keys will work like you describe. However, I admit that this is not smooth. I will take a look at it, but I don't think I'll deal with this by 0.6.

**Comment by PeterSurda** [comment]
Oh wait a minute, you're right. It only works in the messages tab, but not in subscriptions or chans. I'll look at it tomorrow.

**Comment by mailchuck** [comment]
I see you're using the windows version. If you're using the executable, you need to wait until I make a new release with accumulated fixes. That should be this weekend. If you have python installed, you can check out the latest master branch and run it manually.

**Comment by Neui** [comment]
```
Neui@NEUII /B/bitmsg
$ git clone https://github.com/mailchuck/PyBitmessage.git PyBitMsgNewInterfaceS
ource
Cloning into 'PyBitMsgNewInterfaceSource'...
remote: Counting objects: 6743, done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 6743 (delta 49), reused 0 (delta 0), pack-reused 6672
Receiving objects: 100% (6743/6743), 3.88 MiB | 698.00 KiB/s, done.
Resolving deltas: 100% (4476/4476), done.
Checking connectivity... done.

Neui@NEUII /B/bitmsg
$ cd PyBitMsgNewInterfaceSource/

Neui@NEUII /B/bitmsg/PyBitMsgNewInterfaceSource (master)
$ ls
COPYING     README.md    debian     ebuildpackage  puppy.sh      slack.sh
INSTALL.md  arch.sh      debian.sh  generate.sh    puppypackage  slackpackage
LICENSE     archpackage  desktop    man            rpm.sh        src
Makefile    configure    ebuild.sh  osx.sh         rpmpackage

Neui@NEUII /B/bitmsg/PyBitMsgNewInterfaceSource (master)
$ python ./src/bitmessagemain.py
```

Just tested (master), it works.
