### ISSUE TITLE
Adding an entry into addressbook / changing the label does not change existing messagelists

### ISSUE THREAD

**Issue by mailchuck** [mailchuck/PyBitmessage#69]
It was done originally, but does not comprehend the new UI with mutiple messagelists.
- [ ] It should auto-update the list without having to click away and back.
- [ ] also, subscribing to a chan should update addressbook
- [ ] updating a chan name should rerender messagelist
- [ ] updating an entry in identities should upate send from combo box (I think it did but not anymore)

**Comment by PeterSurda** [comment]
~~Disabled with 74d6e6cbf517f9b8537835cf3b99bb5d42ed1f5a until fixed (it consumes too much resources)~~ Wrong commit.
