### ISSUE TITLE
Chans/subscriptions editable through addressbook

### ISSUE THREAD

**Issue by mailchuck** [mailchuck/PyBitmessage#76]
- [x] I think it's broken at the moment.
- [x] ~~Enabling~~/disabling subscription does not update addressbook,
- [x] and does not autosort the tree
- [x] Occasionally, changing a chan label in addressbook does not update messagelist. I think this happens because changing the data in keys.dat and refreshing the messagelist happen almost in parallel and sometimes the messagelist updates first. It's a minor annoyance, postponing for 0.8.

**Comment by PeterSurda** [comment]
Occasionally, changing a chan label in addressbook does not update messagelist. I think this happens because changing the data in keys.dat and refreshing the messagelist happen almost in parallel and sometimes the messagelist updates first. It's a minor annoyance, postponing for 0.8.

**Comment by PeterSurda** [comment]
Also, enabling/disabling subscription does not update addressbook.
