### ISSUE TITLE
ebuild outdated

### ISSUE THREAD

**Issue by ghost** [mailchuck/PyBitmessage#81]
https://github.com/mailchuck/PyBitmessage/blob/master/INSTALL.md
and upstream too if I remember correctly.
I can provide an updated version soon.

this is an package maintaining issue - portage has fallen asleep on some packages, so I think it's easier to not link to portage. They did not hear about the 0.5 release yet. It's in portage, but the ebuild can be improved.

**Comment by mailchuck** [comment]
For gentoo please check this: https://github.com/Bitmessage/PyBitmessage/issues/331

I plan to fix this before 0.6 is released. The 0.5 is in a different repository for various reasons, but I don't want people to mix them.

**Comment by ghost** [comment]
right, I forgot that it's only an ebuild, not more. the removal makes sense.
